version: '3.1'

services:
  web:
    image: docker.studyum.net/web
    restart: always
    # noinspection ComposeUnknownKeys
    pull_policy: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./ssl:/srv/ssl:r
