name: CI-CD

on:
  push:
    branches: [ master ]

  workflow_dispatch:
    inputs:
      version:
        description: 'Image version'
        required: true

env:
  IMAGE_NAME: "studyum"

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Digital Ocean droplet via SSH action
        uses: appleboy/ssh-action@v0.1.3

        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHKEY }}
          passphrase: ${{ secrets.PASSPHRASE }}

          envs: GITHUB_REPOSITORY, IMAGE_NAME

          script: |
            rm -r ${GITHUB_REPOSITORY#*/}
            git clone git@github.com:${{ github.repository }}.git
            cd ${GITHUB_REPOSITORY#*/}
            docker build -t ${IMAGE_NAME} .
            docker run \
            -d -p 80:80 -p 443:443
            --restart always \
            --name ${IMAGE_NAME} \
            ${IMAGE_NAME}
